import { RouteOption, Station, Language } from './types';

export const ROUTES_DATA: RouteOption[] = [
  // --- กะเช้า (Morning Shift) ---
  // ขามา (Inbound)
  { id: 'm1', name: 'สายอยุธยา (รับเช้า)', time: '06:00', type: 'morning', maxSeats: 40, stationIds: ['s5'] },
  { id: 'm2', name: 'สายสระบุรี (รับเช้า)', time: '06:00', type: 'morning', maxSeats: 40, stationIds: ['s4'] },
  { id: 'm3', name: 'สายรังสิต (รับเช้า)', time: '06:00', type: 'morning', maxSeats: 40, stationIds: ['s2'] },
  { id: 'm4', name: 'สายนวนคร (รับเช้า)', time: '06:15', type: 'morning', maxSeats: 40, stationIds: ['s3'] },

  // ขากลับ ปกติ 17:00 (Outbound Normal)
  { id: 'mn1', name: 'สายรังสิต (เลิกงาน)', time: '17:00', type: 'evening', maxSeats: 40, stationIds: ['s2'] },
  { id: 'mn2', name: 'สายอยุธยา (เลิกงาน)', time: '17:00', type: 'evening', maxSeats: 40, stationIds: ['s5'] },
  { id: 'mn3', name: 'สายสระบุรี (เลิกงาน)', time: '17:00', type: 'evening', maxSeats: 40, stationIds: ['s4'] },

  // ขากลับ OT 17:30+ (Outbound OT)
  { id: 'mo1', name: 'สายรวม (OT)', time: '17:30', type: 'evening', maxSeats: 40, stationIds: ['s1'] },
  { id: 'mo2', name: 'สายอยุธยา (OT)', time: '19:45', type: 'evening', maxSeats: 40, stationIds: ['s5'] },
  { id: 'mo3', name: 'สายสระบุรี (OT)', time: '19:45', type: 'evening', maxSeats: 40, stationIds: ['s4'] },
  { id: 'mo4', name: 'สายนวนคร (OT)', time: '20:45', type: 'evening', maxSeats: 40, stationIds: ['s3'] },

  // --- กะดึก (Night Shift) ---
  // ขามา (Inbound)
  { id: 'n1', name: 'สายอยุธยา (เข้ากะดึก)', time: '18:45', type: 'evening', maxSeats: 40, stationIds: ['s5'] },
  { id: 'n2', name: 'สายนวนคร (เข้ากะดึก)', time: '18:45', type: 'evening', maxSeats: 40, stationIds: ['s3'] },
  { id: 'n3', name: 'สายสระบุรี (เข้ากะดึก)', time: '19:45', type: 'evening', maxSeats: 40, stationIds: ['s4'] },

  // ขากลับ ปกติ 05:00 (Outbound Normal)
  { id: 'nn1', name: 'สายสระบุรี (เลิกกะดึก)', time: '05:00', type: 'morning', description: 'ส่งบ้าน', maxSeats: 20, stationIds: ['s4'] },
  { id: 'nn2', name: 'สายนวนคร (เลิกกะดึก)', time: '05:00', type: 'morning', description: 'ส่งบ้าน', maxSeats: 20, stationIds: ['s3'] },
  { id: 'nn3', name: 'สายอยุธยา (เลิกกะดึก)', time: '05:00', type: 'morning', description: 'ส่งบ้าน', maxSeats: 20, stationIds: ['s5'] },

  // ขากลับ OT 05:30+ (Outbound OT)
  { id: 'no1', name: 'สายรวม (OT กะดึก)', time: '05:30', type: 'morning', maxSeats: 20, stationIds: ['s1'] },
  { id: 'no2', name: 'สายสระบุรี (OT กะดึก)', time: '08:00', type: 'morning', description: 'หลัง OT ยาว', maxSeats: 20, stationIds: ['s4'] },
  { id: 'no3', name: 'สายอยุธยา (OT กะดึก)', time: '08:00', type: 'morning', description: 'หลัง OT ยาว', maxSeats: 20, stationIds: ['s5'] },
];

export const STATIONS_DATA: Station[] = [
  { id: 's1', name: 'หน้าบริษัท (Main Gate)', lat: 13.7563, lng: 100.5018, description: 'จุดรวมพลหลักประตู 1' },
  { id: 's2', name: 'ตลาดรังสิต', lat: 13.9897, lng: 100.6177, description: 'ป้ายรถเมล์หน้าตลาด' },
  { id: 's3', name: 'โลตัส นวนคร', lat: 14.1205, lng: 100.6139, description: 'ลานจอดรถด้านหลัง' },
  { id: 's4', name: 'บขส. สระบุรี', lat: 14.5287, lng: 100.9108, description: 'ชานชาลาที่ 4' },
  { id: 's5', name: 'โรบินสัน อยุธยา', lat: 14.3364, lng: 100.6148, description: 'หน้าทางเข้าหลัก' },
];

export const TRANSLATIONS = {
  [Language.TH]: {
    login: 'เข้าสู่ระบบ',
    register: 'ลงทะเบียน',
    empId: 'รหัสพนักงาน',
    fullName: 'ชื่อ-นามสกุล',
    dept: 'แผนก',
    phone: 'เบอร์โทร',
    loginBtn: 'เข้าสู่ระบบ',
    registerBtn: 'ลงทะเบียน',
    home: 'หน้าหลัก',
    booking: 'จองรถ',
    map: 'แผนที่',
    profile: 'โปรไฟล์',
    admin: 'ผู้ดูแล',
    bookShuttle: 'จองรอบรถ',
    mapGps: 'แผนที่จุดขึ้นรถ (GPS Map)',
    currentStatus: 'สถานะการจองปัจจุบัน',
    history: 'ประวัติการจอง',
    news: 'ข่าวประชาสัมพันธ์',
    contact: 'ติดต่อเจ้าหน้าที่',
    selectRoute: 'เลือกเส้นทาง',
    selectStation: 'เลือกจุดขึ้นรถ',
    confirmBooking: 'ยืนยันการจอง',
    available: 'ว่าง',
    seats: 'ที่นั่ง',
    success: 'จองสำเร็จ!',
    registerSuccess: 'ลงทะเบียนสำเร็จ! เข้าสู่ระบบอัตโนมัติ',
    userNotFound: 'ไม่พบผู้ใช้งาน กรุณาลงทะเบียน',
    userExists: 'รหัสพนักงานนี้ลงทะเบียนแล้ว',
    fillAll: 'กรุณากรอกข้อมูลให้ครบถ้วน',
    cancel: 'ยกเลิก',
    cancelled: 'ยกเลิกแล้ว',
    booked: 'จองแล้ว',
    waiting: 'รอขึ้นรถ',
    completed: 'เรียบร้อย',
    full: 'เต็ม',
    distance: 'ระยะทาง',
    navigate: 'นำทาง',
    morning: 'รอบเช้า',
    evening: 'รอบเย็น',
    night: 'กะดึก',
    scanQr: 'สแกน QR Code',
    passengerList: 'รายชื่อผู้โดยสาร',
    export: 'ส่งออกข้อมูล',
    logout: 'ออกจากระบบ',
    hello: 'สวัสดี',
    myQr: 'QR ของฉัน',
    checkInSuccess: 'เช็คชื่อสำเร็จ',
    noBookings: 'ไม่มีการจองที่รอดำเนินการ',
    adminDashboard: 'แดชบอร์ดผู้ดูแล',
    totalBookings: 'ยอดจองวันนี้',
    noAccount: 'ยังไม่มีบัญชี? ลงทะเบียน',
    haveAccount: 'มีบัญชีแล้ว? เข้าสู่ระบบ',
    shiftMorning: 'กะเช้า (Morning Shift)',
    shiftNight: 'กะดึก (Night Shift)',
    inboundWork: 'ขามาทำงาน (To Work)',
    outboundNormal: 'กลับปกติ (Return - No OT)',
    outboundOT: 'กลับหลัง OT (Return - OT)',
    confirmCancel: 'ยืนยันการยกเลิกการจอง?',
    pickup: 'รับ (Pick-up)',
    dropoff: 'ส่ง (Drop-off)',
    selectDates: 'เลือกวันที่เดินทาง',
    daysSelected: 'เลือกแล้ว',
    days: 'วัน',
    confirmMulti: 'ยืนยันการจอง',
    alreadyBooked: 'จองแล้ว',
    todaysTrips: 'รายการเดินทางวันนี้',
    noTripsToday: 'ไม่มีรายการเดินทางวันนี้',
    upcomingTrips: 'รายการจองล่วงหน้า',
    viewAll: 'ดูทั้งหมด',
  },
  [Language.EN]: {
    login: 'Login',
    register: 'Register',
    empId: 'Employee ID',
    fullName: 'Full Name',
    dept: 'Department',
    phone: 'Phone Number',
    loginBtn: 'Login',
    registerBtn: 'Register',
    home: 'Home',
    booking: 'Book',
    map: 'Map',
    profile: 'Profile',
    admin: 'Admin',
    bookShuttle: 'Book Shuttle',
    mapGps: 'Pickup Points Map',
    currentStatus: 'Current Status',
    history: 'History',
    news: 'News & Announcements',
    contact: 'Contact Support',
    selectRoute: 'Select Route',
    selectStation: 'Select Pickup Point',
    confirmBooking: 'Confirm Booking',
    available: 'Available',
    seats: 'seats',
    success: 'Booking Successful!',
    registerSuccess: 'Registration Successful! Logging in...',
    userNotFound: 'User not found, please register',
    userExists: 'User already exists',
    fillAll: 'Please fill all fields',
    cancel: 'Cancel',
    cancelled: 'Cancelled',
    booked: 'Booked',
    waiting: 'Waiting',
    completed: 'Completed',
    full: 'Full',
    distance: 'Distance',
    navigate: 'Navigate',
    morning: 'Morning',
    evening: 'Evening',
    night: 'Night Shift',
    scanQr: 'Scan QR Code',
    passengerList: 'Passenger List',
    export: 'Export Data',
    logout: 'Logout',
    hello: 'Hello',
    myQr: 'My QR',
    checkInSuccess: 'Check-in Successful',
    noBookings: 'No pending bookings',
    adminDashboard: 'Admin Dashboard',
    totalBookings: 'Total Bookings Today',
    noAccount: 'No account? Register',
    haveAccount: 'Have an account? Login',
    shiftMorning: 'Morning Shift',
    shiftNight: 'Night Shift',
    inboundWork: 'To Work',
    outboundNormal: 'Return (No OT)',
    outboundOT: 'Return (OT)',
    confirmCancel: 'Are you sure you want to cancel?',
    pickup: 'Pick-up (Inbound)',
    dropoff: 'Drop-off (Outbound)',
    selectDates: 'Select Travel Dates',
    daysSelected: 'Selected',
    days: 'days',
    confirmMulti: 'Confirm Bookings',
    alreadyBooked: 'Booked',
    todaysTrips: "Today's Trips",
    noTripsToday: 'No trips scheduled for today',
    upcomingTrips: 'Upcoming trips',
    viewAll: 'View All',
  }
};